### ISSUE TITLE
breakfast oneplus3 not working

### ISSUE THREAD

**Issue by nanu-c** [Vince1171/OnePlus3-T-Halium-Prebuild#10]
```
(oneplus3) nanu@nanu:~/src/ut/oneplus3$ breakfast oneplus3
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_oneplus3".  Schluss.
build/core/product_config.mk:249: *** Can not locate config makefile for product "cm_oneplus3".  Schluss.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_oneplus3".  Schluss.
Device oneplus3 not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_oneplus3
Traceback (most recent call last):
  File "vendor/cm/build/tools/roomservice.py", line 263, in <module>
    default_revision = get_default_revision()
  File "vendor/cm/build/tools/roomservice.py", line 117, in get_default_revision
    return r.replace('refs/heads/', '').replace('refs/tags/', '')
AttributeError: 'NoneType' object has no attribute 'replace'
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_oneplus3".  Schluss.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_oneplus3".  Schluss.

** Don't have a product spec for: 'lineage_oneplus3'
** Do you have the right repo manifest?

```

**Comment by nanu-c** [comment]
complete log:
https://pastebin.ubuntu.com/p/yp3rQbk95Z/

**Comment by nanu-c** [comment]
as noted in http://docs.halium.org/en/latest/porting/build-sources.html#for-halium-7-1 so i tried the command.
`breakfast halium_oneplus3-eng` worked and `lunch halium_oneplus3-eng`, too. Maybe add this to your doc here?

**Comment by j6s** [comment]
I ran into this exact problem and the solution was that the 'codename' means something else than I thought it would. Let me lookup the IRC chatlogs for when I  asked about this.

**Comment by j6s** [comment]
Here we go.
The correct codename is `halium_oneplus3-userdebug`

```
<j6s2> Sorry about that - my last message as j6s was formatted weirdly by my IRC client which
lead to me being banned for spamming. Don't know how much went through, but I am currently
having issues building halium for oneplus3 - where breakfast cannot find the correct makefiles /
product spec.  I don't know much about the build system and thus would need a pointer on where 
I would have to look for those makefiles
[...]
<Vince> @j6s2 breakfast halium_oneplus3-userdebug
<j6s2> Oh, I was wondering if I misread "[codename]" in the manual. That actually works. Thanks
```

**Comment by Vince1171** [comment]
@nanu-c and be sure to use my repo and not the halium one and use the ubp-7.1 branch
(I haven't pushed my code to halium because it break Plasma mobile)

**Comment by nanu-c** [comment]
I used the manifesto from the description. https://gist.github.com/Vince1171/e1aa5fda8dda213f909f71ef70de0792
I had comment out `sysfs_devices_system_iosched` in `vendor/cm/sepolicy/qcom/mpdecision.te` and perfd.te then the build finished and now i am flashing. Should i change the revision="halium-7.1" to ubp-7.1?

**Comment by Vince1171** [comment]
oh I forgot to modify the gist sorry, I fix it right now
yes you have to change halium-7.1 to ubp-7.1

**Comment by Vince1171** [comment]
or you can go to
kernel/oneplus/msm8996
and device/oneplus/oneplus3
and do 
`git fetch vince`
`git checkout ubp-7.1`
